### ISSUE TITLE
Issue left for Milestone 1

### ISSUE THREAD

**Issue by milicmil** [UBC-MDS/exploreR#2]
We need to add:

- [x] Add contributing.md

- [x] Add code of conduct

- [x] Define individual roles in regards to individual function writing

- [x] Add placeholder folders for the directory structure (data src imgs docs)

- [x] Add empty function files (3 empty R files)

- [x] generate and document blackbox test cases

**Comment by rachelkriggs** [comment]
all items addressed.
